# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  projects:
    - name: proxy
      url: https://github.com/KalleDK/py-keyring-proxy.git
    - name: cli
      url: https://github.com/KalleDK/py-keyring-proxy-cli.git
    - name: env
      url: https://github.com/KalleDK/py-keyring-proxy-env.git
    - name: socket
      url: https://github.com/KalleDK/py-keyring-proxy-socket.git
    - name: stdio
      url: https://github.com/KalleDK/py-keyring-proxy-stdio.git

includes:
  proxy:
    taskfile: ./py-keyring-proxy/taskfile.yml
    dir: ./py-keyring-proxy
    optional: true
  cli:
    taskfile: ./py-keyring-proxy-cli/taskfile.yml
    dir: ./py-keyring-proxy-cli
    optional: true
  env:
    taskfile: ./py-keyring-proxy-env/taskfile.yml
    dir: ./py-keyring-proxy-env
    optional: true
  stdio:
    taskfile: ./py-keyring-proxy-stdio/taskfile.yml
    dir: ./py-keyring-proxy-stdio
    optional: true
  socket:
    taskfile: ./py-keyring-proxy-socket/taskfile.yml
    dir: ./py-keyring-proxy-socket
    optional: true

tasks:
  pull_single:
    internal: true
    dir: '{{ .DIR }}'
    cmds:
      - echo "Pulling {{ .NAME }}"
      - git pull
  
  pull:
    cmds:
      - for:
          var: projects
        task: pull_single
        vars:
          NAME: '{{.ITEM.name}}'
          DIR: '{{ .ITEM.url | splitList "/" | last | splitList "." | first }}'
    
  clone_single:
    internal: true
    cmds:
      - echo "Cloning {{ .NAME }}"
      - git clone {{ .URL }}
    status:
      - test -d {{ .URL | splitList "/" | last | splitList "." | first }}

  clone:
    cmds:
      - for:
          var: projects
        task: clone_single
        vars:
          NAME: '{{.ITEM.name}}'
          URL: '{{.ITEM.url}}'

  update:
    cmds:
      - for: 
          var: projects
        task: '{{.ITEM}}:update'

  init:
    cmds:
      - for: 
          var: projects
        task: '{{.ITEM.name}}:init'
  
  devrel_single:
    internal: true
    cmds:
      - task: '{{.NAME}}:update'
      - task: '{{.NAME}}:devrel'

  devrel:
    cmds:
      - for: 
          var: projects
        task: devrel_single
        vars:
          NAME: '{{.ITEM.name}}'
    
  release_single:
    internal: true
    cmds:
      - task: '{{.NAME}}:update'
      - task: '{{.NAME}}:release'

  release:
    cmds:
      - for: 
          var: projects
        task: release_single
        vars:
          NAME: '{{.ITEM.name}}'

  sync:
    cmds:
      - for: 
          var: projects
        task: '{{.ITEM.name}}:sync'

  default:
    cmds:
      - task: clone
      - code keyring.code-workspace

