version: '3'

vars:
  projects:
    - proxy
    - cli
    - env
    - socket
    - stdio

includes:
  proxy:
    taskfile: ../py-keyring-proxy/taskfile.yml
    dir: ../py-keyring-proxy
  cli:
    taskfile: ../py-keyring-proxy-cli/taskfile.yml
    dir: ../py-keyring-proxy-cli
  env:
    taskfile: ../py-keyring-proxy-env/taskfile.yml
    dir: ../py-keyring-proxy-env
  stdio:
    taskfile: ../py-keyring-proxy-stdio/taskfile.yml
    dir: ../py-keyring-proxy-stdio
  socket:
    taskfile: ../py-keyring-proxy-socket/taskfile.yml
    dir: ../py-keyring-proxy-socket

tasks:
  update:
    cmds:
      - for: 
          var: projects
        task: '{{.ITEM}}:update'

  init:
    cmds:
      - for: 
          var: projects
        task: '{{.ITEM}}:init'
  
  devrel_single:
    cmds:
      - task: '{{.PROJECT}}:update'
      - task: '{{.PROJECT}}:devrel'

  devrel:
    cmds:
      - for: 
          var: projects
        task: devrel_single
        vars:
          PROJECT: '{{.ITEM}}'
    
  release_single:
    cmds:
      - task: '{{.PROJECT}}:update'
      - task: '{{.PROJECT}}:release'

  release:
    cmds:
      - for: 
          var: projects
        task: release_single
        vars:
          PROJECT: '{{.ITEM}}'